blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/osrsprofittracker/OSRSProfitTracker/discussions
    about: For general questions use GitHub Discussions instead of opening an issue.